### ISSUE TITLE
Nextflow pipeline fails with bonferroni integration strategy

### ISSUE THREAD

**Issue by sweavs111** [timothy-barry/sceptre-pipeline#3]
Hello,

I am running the nextflow pipeline, and it is failing at the run_qc step when I use the bonferroni gRNA integration strategy. The pipeline runs just fine for me if I remove the `--grna_integration_strategy bonferroni` argument from the nextflow script (therefore using "union") and completes. Same exact input files used. Is this a known issue? Is there anything I can do to fix it? 

I tracked down the bug to the run_qc.R file line 43:
`sceptre_object <- do.call(what = sceptre::run_qc, args = args_to_pass)`

I tried to look into it further but got stuck.

See screenshot and nextflow error message:

```
ERROR ~ Error executing process > 'run_qc'

Caused by:
  Process `run_qc` terminated with an error exit status (1)


Command executed:

  run_qc.R sceptre_object_fp   response_odm_fp   grna_odm_fp   default   default   default   default   default   default   default

Command exit status:
  1

Command output:
  [1] "1"
  [1] "2"

Command error:
  [1] "1"
  [1] "2"
  Error in `[.data.frame`(x, i, j) : undefined columns selected
  Calls: do.call ... compute_pairwise_qc_information -> [ -> [.data.table -> [.data.frame
  Execution halted

Work dir:
  /Users/sethweaver/Downloads/hsSD/crispri/outputSeq/sceptre/atScale/work/27/b8e5a5ef33df9ee70519081bb1ef67

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

Let me know if you would like me to send over any of my .rds or .odm files for replicating the error.
Thanks!

![Screenshot 2024-06-04 at 12 42 27 PM](https://github.com/timothy-barry/sceptre-pipeline/assets/70345529/1ff307a1-e326-4abd-8800-8728cb4e73aa)

**Comment by ekatsevi** [comment]
I get the same error with `--grna_integration_strategy singleton`.

**Comment by timothy-barry** [comment]
Thank you both for identifying this bug. I will take a look in the near future and get back to you!

**Comment by timothy-barry** [comment]
Hi Seth,

Thank you for your detailed report. I think I fixed the problem. Could you download and install the latest version of the `sceptre` package and try again?

**Comment by sweavs111** [comment]
Hey Tim,

I ran the trial pipeline with both bonferroni and singleton integration methods and it completed. Thanks for the quick fix!

**Comment by timothy-barry** [comment]
Great Seth, let us know if you encounter any other issues with the pipeline.
